name: Build APKs (Early Release)

on:
    workflow_dispatch:  # Allow manual triggering

jobs:
    build:
        name: Build Early Release APK
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Java and Android SDK
                uses: actions/setup-java@v3
                with:
                    java-version: '17' # Adjust the Java version as needed
                    distribution: 'temurin'
                    cache: 'gradle'

            -   name: Decode Keystore
                id: decode_keystore
                uses: timheuer/base64-to-file@v1
                with:
                    fileName: 'keystore/key.jks'
                    encodedString: ${{ secrets.SIGN_KEY }}

            -   name: Build GitHub Release APK
                run: |
                    chmod +x ./gradlew
                    ./gradlew clean assembleGithubRelease
                env:
                    SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
                    SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                    SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

            -   name: Build Play Release APK
                run: |
                    chmod +x ./gradlew
                    ./gradlew clean assemblePlayRelease
                env:
                    SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
                    SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                    SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

            # If you want to build both APKs in parallel, uncomment the following lines

            #            -   name: Build GitHub Release and Play Release APKs
            #                run: |
            #                    chmod +x ./gradlew
            #                    ./gradlew clean assembleGithubRelease assemblePlayRelease --parallel
            #                env:
            #                    SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
            #                    SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
            #                    SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

            -   name: Archive APKs
                uses: actions/upload-artifact@v3
                with:
                    name: Release APKs
                    path: |
                        app/**/play/release/*.apk
                        app/**/github/release/*.apk
